################################################################################
#
# THIS FILE IS BASIC MAKE FILE FOR
# Copyright (c) 2020-2021
# Original Author: 1107473010@qq.com
#
################################################################################

# This is object should be build and will link to generate
# the executables
objects = stack_containers.o

# This is the file name of the executables and path where 
# place the executables
executables = studystack
executables_path = ../../../Executables/

# Including this file allows access to the Build System.
include ../../../Build/build.mk