################################################################################
#
# THIS FILE IS BASIC MAKE FILE FOR
# Copyright (c) 2020-2021
# Original Author: 1107473010@qq.com
#
################################################################################

# This is object should be build and will link to generate
# the executables
objects = main.o

# include path
include_path = -I../asio/include

# This is the file name of the executables and path where 
# place the executables
executables = study_asio_basic
executables_path = ../../executables

# Including this file allows access to the Build System.
include ../../build/build.mk