################################################################################
#
# THIS FILE IS BASIC MAKE FILE FOR
# Copyright (c) 2020-2021
# Original Author: 1107473010@qq.com
#
################################################################################

# This is object should be build and will link to generate
# the executables
objects = time.o main.o mem_manage.o

# This is the file name of the executables and path where 
# place the executables
executables = studyboost
executables_path = ../../Executables
INCLUDE_PATH = -I D:/Software/boost/include/boost-1_80

# Including this file allows access to the Build System.
include ../../Build/build.mk